### ISSUE TITLE
Login page (S2)

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#12]
# Description

The login page will be the index of the applications for non-authenticated users. It will require the `username` and `password` fields to access to the platform.

The login page will have a `Register` button redirecting to the registration page. #5 

## Tasks

- [x] Create the Login page and its validation. (H3-2)
- [x] Create the API method to log in. Done in https://github.com/davidcr01/TFG/issues/4#issuecomment-1568173031
- [x] Create the controller of the Login page. (H3-1)

**Comment by davidcr01** [comment]
# Update Report

The mockup for this page is the following, done in Figma:
![2](https://github.com/davidcr01/WordlePlus/assets/72193239/0d3b2d8c-9346-4377-bc6a-5b03fda35c48)

The page is generated with the `ionic g page pages/login`.

**Comment by davidcr01** [comment]
# Update Report

## Home page

A new page `Home` has been created. This page only show a loading icon, and it redirects the user depending on his token. If a token is stored, is redirected to the main application (tabs right now). If not, is redirected to the login page.

```
export class HomePage {

  constructor(private router: Router, private storageService: StorageService) { }

  ionViewDidEnter() {

    setTimeout(async () => {
      const token = await this.storageService.getAccessToken();
      console.log(token);
      
      if (!token) {
        // Redirigir al usuario a la página de inicio de sesión
        this.router.navigateByUrl('/login');
      } else {
        this.router.navigateByUrl('/tabs');
      }
    }, 2000);


  }

}
```

Notice that the `ionViewDidEnter` is used. This method is executed when the page has loaded.

To always load the Home page at the beginning of the app and when a URL does not exist, a new route has been added to the `app-routing.module.ts`:

```
const routes: Routes = [
  {
    path: '',
    redirectTo: 'home',
    pathMatch: 'full'
  },

```

**Comment by davidcr01** [comment]
# Update Report

## Result

When opening the app, this page is shown:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/f95fa57d-265f-43fe-8409-7e8c50d2f2a2)

When some seconds have passed, the login page is shown:

![image](https://github.com/davidcr01/WordlePlus/assets/72193239/f8845ee9-b7e7-4fda-b950-1cdff56a431e)

✔️ If the credentials are not correct, an error is displayed:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/3793eaa7-1df9-4597-b7a6-d41f35c9b43d)

✔️ If the credentials are correct, the token is stored and the user is redirected to the application itself:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/d15d2146-89a5-4329-a18b-751b92b3e3be)

The `tabs` pages are provisional right now, but the redirection works.

If we navigate to the main page (http://localhost), the home page (loading page) is shown and the user is redirected again to the `tabs` page as the token has been stored.
