### ISSUE TITLE
Customize the User and Players model (S1)

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#3]
## Description

Django provides a default User model: https://docs.djangoproject.com/en/4.1/ref/contrib/auth/.

But it is needed to adapt this User model to one that fits with the project. Some of the default fields are not necessary, but it is necessary to add a new field `avatar` to the User model.

Besides, it is necessary to create the `Player` model, defined in the Database analysis of the project.

## Tasks

- [x] Create a custom User model and its serializer. (H1-3, H1-4)
- [x] Create Players model and its serializer (H1-1, H1-2, H1-5)
- [x] Add them to the admin site. 
- [x] Insert some rows as a test.
- [x] Fetch the rows with an API call to test the save and retrieve action works.

Note: the H2-1, H2-2, and H2-3 are implemented in the User model and serializer, as they will be identified by the `is_staff` field.

## Extra tasks

- [x] Securize the password.
- [x] The username field is read_only just while editing the information.
