### ISSUE TITLE
Tournament creation (S5)

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#34]
# Description

Is necessary for the admins to create an open tournament. This tournament will be opened to the rest of the players.

## Tasks

- [x] Define the model of the tournament room (H7-1).
- [x] Define the automatic insertion of the tournament room in the BBDD (H7-2).
- [x] Define the related controller. (H7-3)
- [x] Implement the UI of the creation of the tournament room. (H7-4)
