### ISSUE TITLE
Customize the Users authentication (S1)

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#4]
## Description

Once the User model and Players models are created and tested (https://github.com/davidcr01/TFG/issues/3) it is necessary to modify the permissions of these users in order to securitize the API methods. Players should have access to a group of API calls and Administrators to another group of API calls.
And every non-authenticated user must not have access to any of the API methods.

Some interesting links are:
- https://python.plainenglish.io/django-token-authentication-with-custom-user-model-2d780237bc4
- https://sdh.global/blog/itconsulting/custom-permissions-django/

## Tasks

- [x] Create a permission group for the Players. **Replaced by the is_staff logic.**
- [x] Create a permission group for the Admins. **Replaced by the is_staff logic.**
- [x] Create an API call to allow the users to log in to the app.
- [x] Test them.
- [x] Test that a non-authenticated user can not use the API.
