### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#5]
## Description

The register page will display all the necessary fields to create an user. The form should be validate before inserting the user in the backend.
To register the administrators (event managers), they will have to insert a staff code given by the superuser. This is a straightforward security method to register authorized staff members. To perform this, is necessary to create a new model that stores some codes.

## Tasks

- [x] Create StaffCode model.
- [x] Create the Register page. (H1-6, H2-4 as the player and user creation are done in the same form)
- [x] Create the API method to register a user.
- [x] Create the serializer for the user.
- [x] Create the serializer for the players.

Some of the tasks in the description were done in previous issues:
- Create the API method to register a user. https://github.com/davidcr01/TFG/issues/3#issuecomment-1550201322
- Create the serializer for the users. https://github.com/davidcr01/TFG/issues/3#issuecomment-1550201322
- Create the serializer for the players. https://github.com/davidcr01/TFG/issues/3#issuecomment-1550201322
