### ISSUE TITLE
Multiplayer (S8)

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/WordlePlus#50]
# Description

As a player, it is necessary to implement new functionality to play the wordle game with another player.

## Tasks

- [x] Define the model of the multiplayer games. (HU11-1)
- [x] Define the controller created to the creation of the multiplayer game. (HU11-2)
- [x] Implement the UI related to the multiplayer game.  (HU11-3)
- [x] Implement the UI related to the accepting of the game  (HU11-4)
- [x] Send the notification to the player.  (HU11-5)

**Comment by davidcr01** [comment]
# Update Report - DRF

A new model has been added to store the multiplayer games called `Games`:
```
class Game(models.Model):
    player1 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='player1_wordle')
    player2 = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='player2_wordle')
    word = models.CharField(max_length=255)
    player1_time = models.PositiveIntegerField(default=0)
    player1_attempts = models.PositiveIntegerField(default=0)
    player1_xp = models.PositiveIntegerField(default=0)
    player2_time = models.PositiveIntegerField(default=0)
    player2_attempts = models.PositiveIntegerField(default=0)
    player2_xp = models.PositiveIntegerField(default=0)
    winner = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True, blank=True, related_name='winner')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.player1.user.username} - {self.player2.user.username}"
```

The serializer looks like this:
```
class GameSerializer(serializers.ModelSerializer):
    class Meta:
        model = Game
        fields = ['id', 'player2', 'player1_time', 'player2_time', 'player1_xp',
                  'player2_xp', 'timestamp', 'word', 'player1_attempts', 'player2_attempts',
                  'winner']
```
Notice that the player1 is not managed as is the player that creates the game, and it is fetched by the identified player.
 
About the view, the `create` method (executed by the player that creates the game) only allows the player1 statistics. To correctly create the game and link it to the player2, the ID of the second player must be included in the body.

```
def create(self, request, *args, **kwargs):
        player1 = getattr(request.user, 'player', None)
        if not player1:
            return Response({'error': 'Player1 not found'}, status=404)
        player2_id = request.data.get('player2')

        if not player2_id:
            return Response({'error': 'player2 parameter is required'}, status=400)

        try:
            player2 = Player.objects.get(id=player2_id)
        except Player.DoesNotExist:
            return Response({'error': 'Player2 not found'}, status=status.HTTP_404_NOT_FOUND)

        allowed_fields = ['player2', 'player1_xp', 'player1_time', 'player1_attempts', 'word']
        data = {key: request.data.get(key) for key in allowed_fields}

        if 'winner' in data:
            return Response({'error': 'The "winner" field cannot be modified.'}, status=400)
        
        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)

        serializer.save(player1=player1, player2=player2)

       # Create notification to the guest player
        Notification.objects.create(
            player=player2,
            text=f"You have been challenged by {player1.user.username}. Let's play!",
            link=''
        )

        return Response(serializer.data, status=201)
```
About the PATCH method, executed by the second player (when it accepts the challenge), it adds the information that is left and defines the winner.

```
def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        player = request.user.player

        if instance.player2 != player:
            return Response({'error': 'You do not have permission to update this game.'}, status=403)

        allowed_fields = ['player2_xp', 'player2_time', 'player2_attempts']
        data = {key: request.data.get(key) for key in allowed_fields}

        if 'winner' in data:
            return Response({'error': 'The "winner" field cannot be modified.'}, status=400)

        player2_xp = request.data.get('player2_xp')
        if player2_xp is not None:
            player1_xp = instance.player1_xp
            if player2_xp > player1_xp:
                instance.winner = instance.player2
            elif player2_xp < player1_xp:
                instance.winner = instance.player1
            else:
                instance.winner = None

        serializer = self.get_serializer(instance, data=data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response({'winner': instance.winner.user.username})
```

![image](https://github.com/davidcr01/WordlePlus/assets/72193239/86131d25-45cc-4ca4-a5bf-3e6a2208c470)
Notice how the player2 information is passed to the backend and it ignores it. Besides, the notification is created:

![image](https://github.com/davidcr01/WordlePlus/assets/72193239/4e2bb6d0-b2fd-4fc1-a618-57983cd4954f)

When the second player plays the game, the information is passed to the backend and the winner is calculated and returned:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/0922f223-0f41-4e82-a96b-ee5e774ccb6d)

**Comment by davidcr01** [comment]
# Update Report - Frontend

Three new pages have been generated for the multiplayer:
- createGame: this page is loaded when the user select the player to play the multiplayer. This page receives the opponent username and id as parameter to create the game. When clicking on the play button of the friendlist #47, the words selection popover implemented in #25  is displayed, and redirects the user to the createGame page:

```
<ion-content>
    <div class="game-info">
        <div class="username">{{ selfUsername }}</div>
        <img src="../../../assets/icon/vs.png" alt="VS icon">
        <div class="username">{{ opponentUsername }}</div>
      </div>
    
   <ng-container *ngIf="wordLength">
    <app-wordle-dashboard [WORDS_LENGTH]="wordLength" [isMultiplayer]="true" (gameFinished)="finishGame($event.time, $event.xp, $event.attempts, $event.selectedWord)"></app-wordle-dashboard>
   </ng-container>
</ion-content>

async ngOnInit() {
    this.selfUsername = await this.storageService.getUsername();
    this.route.queryParams.subscribe((params) => {
      this.opponentId = params['opponentId'];
      this.opponentUsername = params['opponentUsername'];
      this.wordLength = parseInt(params['length'],10);
    });
  }

  async finishGame(time: number, xp: number, attempts: number, selectedWord: string) {
    const gameData = {
      player2: this.opponentId,
      player1_time: time,
      player1_xp: xp,
      player1_attempts: attempts,
      word: selectedWord,
    };
    
    (await this.apiService.createGame(gameData)).subscribe(
      (response) => {
        console.log('Game registered successfully', response);
        this.toastService.showToast('Game registered successfully! Who will win?', 2000, 'top', 'success');
        setTimeout(() =>this.router.navigate(['/tabs/main'], { queryParams: { refresh: 'true' } }), 2500);
      },
      (error) => {
        console.error('Error creating game:', error);
      }
    );
```
About the HTML code, it displays the information of the multiplayer game and loads the `wordle-dashboard` component implemented in #22. 
About the TS logic, the finishGame method is executed when the dashboard component emit an event when the first user finishes the game, and the create-game page publish the results in the backend.

```
@Output() gameFinished: EventEmitter<any> = new EventEmitter();
...
// Case of multiplayer game
      if (this.isMultiplayer) {
        const gameFinishedEvent = {
          time: timeConsumed,
          xp: xP,
          attempts: attempsConsumed,
          selectedWord: this.rightGuessString,
        };
        this.gameFinished.emit(gameFinishedEvent);
```

- History page stores all the history of games, classic wordles and PVP games, completed and pending. When a player challenges another player, the game will appear in the pending window. This page is built very similar to the friendlist page #44.

```
<div *ngIf="pendingPvpGames && pendingPvpGames.length > 0">
      <ion-card *ngFor="let game of pendingPvpGames">
        <ion-card-header>
          <ion-icon name="flash"></ion-icon>
          {{ game.player1 }}
          <ion-icon name="flash"></ion-icon>
        </ion-card-header>
        <ion-card-content>
          <ion-list>
            <ion-item>
              <ion-icon name="hourglass-outline" slot="start"></ion-icon>
              <ion-label>Time</ion-label>
              {{ game.player1_time }}"
            </ion-item>
            <ion-item>
              <ion-icon name="text-outline" slot="start"></ion-icon>
              <ion-label>Word length</ion-label>
              {{ game.word.length }} letters
            </ion-item>
          </ion-list>
          <ion-button class="play-button" expand="block" size="default" shape="default" (click)="respondGame(game.id)">
            Play
          </ion-button>
        </ion-card-content>
      </ion-card>
    </div>

async loadPendingPvpGames() {
    try {
      this.pendingPvpGames = await this.apiService.getPendingPVPGames();
    } catch (error) {
      this.toastService.showToast("Error loading pending games", 2000, 'top', 'danger');
    }
  }

  respondGame(idGame: string){
    // Refresh pending games and redirect
    this.loadPendingPvpGames();
    this.router.navigate(['/respond-game'], { queryParams: { idGame: idGame } });
  }
```
The pending games are fetched by a new apiService method called getPendingPVPGames, which fetches the games that the identified player has not played yet, using the `pending_games` route.

When clicking in the "play" button, the `respond-game` page is loaded. This page receives the id of the game as parameter. With the ID, the rest of the information of the game can be fetched and not passed by parameters in the URL:

```
async ngOnInit() {
    this.selfUsername = await this.storageService.getUsername();
    this.route.queryParams.subscribe((params) => {
      this.idGame = params['idGame'];
    });

    (await this.apiService.getGame(this.idGame)).subscribe(
      (response) => {
        console.log(response);
        this.selectedWord = response.word;
        this.opponentUsername = response.player1;
        this.wordLength = this.selectedWord.length;
      },
      (error) => {
        this.showAlert("Ups!", "You can't play this game!");
      }
    );
  }
```

This page also uses the `finishGame` method, but in this case it fetches the player2 statistics and push them to the backend:
```
async finishGame(time: number, xp: number, attempts: number, selectedWord: string) {
    const gameData = {
      player2_time: time,
      player2_xp: xp,
      player2_attempts: attempts,
    };

    (await this.apiService.resolveGame(this.idGame, gameData)).subscribe(
      (response) => {
        console.log('Game resolved successfully', response);
        console.log(response.winner, this.selfUsername);
        if (response.winner === this.selfUsername) {
          setTimeout( () => this.showAlert('Congratulations!', 'You won! Amazing!'), 2500);
        } else {
          setTimeout( () => this.showAlert('Bad news!', 'You lost. Try next time!'), 2500);
        }
        // Handle success and navigate to appropriate page
      },
      (error) => {
        console.log('Game could not be resolved', error);
        // Handle error
      }
    );
```

With this, both pages uses the wordle-dashboard component, which is also used in the classic wordles. This is a very good example of building and reusing a component.

## Results

1. Player challenges testing to a 5 letter game:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/ba521e22-6ff5-4ccc-84d2-45b4691d66b7)

2. Testing see that some pending games are listed in the History page:
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/bcd606e0-6bc9-45ec-be64-c9dd5d0526cd)

3. Testing plays the game. Notice that the word is the same: apple
![image](https://github.com/davidcr01/WordlePlus/assets/72193239/7249131b-7460-42bc-acce-50ebbecd4cdf)
